In [2]:
import pandas as pd
import numpy as np
import pandas as pd 
import numpy as np
import sklearn as sk
from sklearn import tree
import seaborn as sns

#import библиотек настройка окружения

In [3]:
#pip install -U scikit-learn

In [4]:
#pip install seaborn

In [5]:
data = pd.read_csv("train_clear.csv", delimiter="\t")
data.head(3)

,CLIENT_ID,RETRO_DT,tokens,DEF,urls_hashed
0,5909886,20200911,форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...,0,7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...
1,1385448,20210519,platiza 1 мобильные 2 sergej 1 code 3 отказов ...,1,1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...
2,1866195,20210913,sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...,0,6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...

In [6]:
y = data["DEF"]
data = data.drop(['DEF'], axis=1)
data.head(3)

,CLIENT_ID,RETRO_DT,tokens,urls_hashed
0,5909886,20200911,форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...,7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...
1,1385448,20210519,platiza 1 мобильные 2 sergej 1 code 3 отказов ...,1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...
2,1866195,20210913,sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...,6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
data_train, data_test, y_train, y_test = train_test_split(data, y, test_size=0.33, random_state=42)
# разбиение на тренировчоный и тестовый

In [9]:
clf = tree.DecisionTreeClassifier(criterion='entropy')

In [10]:
def waste_digits(dict):

    name_list_split = []

    for name in dict:
        name_list_split.append([name] * dict[name])

    name_list_join = []
    for name_list in name_list_split:
        for name in name_list:
            name_list_join.append(name)

    return name_list_join

In [11]:
array_of_tokens = data['tokens'].to_dict()

In [12]:
data.iloc[:, [2]]

                                                   tokens
0       форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...
1       platiza 1 мобильные 2 sergej 1 code 3 отказов ...
2       sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...
3       code 1 историй 1 scf 1 шаг 1 деньги 3 серый 1 ...
4       отказов 2 tovara 1 сергея 1 купальный 1 чёрный...
...                                                   ...
302863  морковь 1 вред 1 описание 1 калорийность 1 пол...
302864  мотылёк 1 uploader 1 photo 1 провокатор 2 смс ...
302865  чёрный 1 деньги 12 бытовой 1 серый 3 маршрутов...
302866  kabelya 1 pesen 2 статья 2 опубликовала 1 купи...
302867  smartfony 1 шины 4 итак 1 ипотеку 1 сергею 1 с...

[302868 rows x 1 columns]

In [13]:
data['tokens2'] = data['tokens']

In [17]:
data.tokens2[1] = waste_digits(to_dict(data.tokens[1]))

/tmp/ipykernel_1200/366726956.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.tokens2[1] = waste_digits(to_dict(data.tokens[1]))

In [18]:
for i in range(0, 10):
    data['tokens2'][i] = " ".join(waste_digits(to_dict(data.tokens[i])))
print('READY')

READY

/tmp/ipykernel_1200/3215537481.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tokens2'][i] = " ".join(waste_digits(to_dict(data.tokens[i])))

In [19]:
data.head(3)

,CLIENT_ID,RETRO_DT,tokens,urls_hashed,tokens2
0,5909886,20200911,форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...,7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...,форм мачеха работы пасынка горячую массаж маче...
1,1385448,20210519,platiza 1 мобильные 2 sergej 1 code 3 отказов ...,1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...,platiza мобильные мобильные sergej code code c...
2,1866195,20210913,sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...,6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...,sims sims sims кредит языке разлива огромное о...

In [20]:
#clf.fit(

In [15]:
def to_dict(string):
        dictionary = {}
        for i, str_obj in enumerate(string.split()):
            if i % 2 == 0:
                key = str_obj
            else:
                value = str_obj
                dictionary[key] = int(value)
        return dictionary

In [16]:
def dict_to_dict_without_num(dict):
    count = 0
    result = {}
    while dict.get(count):
        result.update(to_dict(dict.get(count)))
        count += 1

    return result

In [21]:
#(data['tokens2'].str.split(' ', expand=True))

In [22]:
#data['tokens2'] = pd.get_dummies(data, columns =['tokens2'])

In [23]:
#clf.fit(data['tokens2'], y)

In [24]:
data['tokens2'][0]

'форм мачеха работы пасынка горячую массаж мачехи kakaya tovari дмб milf milf istoriya парня хуя voyska cvet рода получает слушай molodym porno porno porno телепрограмма видит полоса красивыми сделал горячем мама колледже замужняя varit kendra brigada луна цвет lust зрелой зависимости мужиками работу тельняшка sportivnye баба тельняшки завтра зрелых зрелых молодых американский качестве качестве дом отличаются заставила мать видео видео видео видео видео видео видео видео история clothes активация zavisimosti вместо porn porn неделю летняя бесплатно грудастая предпочитает смотреть смотреть смотреть смотреть смотреть смотреть смотреть смотреть пойти video video video video video video video video viewmsg молодыми отдельной наказания беспла порно порно порно порно порно порно порно порно mama негр полная tube массажиста public poshla аппетитную нежный трахается сиськами бригада теплую mature mature mature mature mature член захотела мамаши форма popular brigady ushli вызвала ranshe genre rus лекси темно расслабиться brat ванну хозяйка зрелые зрелые милашка мачеху мачеху проблем roditeli облако пасынок пасынок ушли пар разговоры утром luna weather trusy групповой соблазняет tomorrow борщ speak русское смотри русский сертификата yekaterinburg seksa русским гламурная настоящие bdsm милф милф русском молодой молодой бригады lexi williams teen urban никто спортивные старая каналы prochee tiger прелести flag купить женщинами женщинами женщинами женщинами женщинами huy bryuki молодого молодого квеста ебётся брюки жанрам соблазнила трусы вдова трусики vozrasta милфа dee выебал baba секс секс секс секс секс секс секс секс полицейская sisyastaya roda пошалим молодые talking родители сына сюжетом выебана молодым hozyayka chase бабы войск приняла надувной передач парень парень парень магазине русскими pensionnogo жирная категории городская lamoda мамаша переводом лучших лучших лучших лучших лучших возрастной трахает трахает популярное деревенский программа мамка vojsk брат студент ekaterinburg уильямс друга друга друга хорошем русскую флаг зрелыми зрелыми зрелыми зрелыми зрелыми зрелыми зрелыми ответы зеленая'

In [25]:
popular = {'работа', 'календарь', 'зарплаты', 'клиентов', 'всей', 'взять', 'home', 'москве', 'program', 'customers', 'secure', 'одноклассники', 'society', 'деньги', 'купить', 'megogo', 'займы', 'contact', 'задачи', 'почта', 'success', 'банк', 'кредит', 'екапуста', 'бесплатно', 'цены', 'application', 'фильмы', 'займ', 'amp', 'карту', 'цене', 'войти', 'ставки', 'сериал', 'игры', 'новости', 'займов', 'компании', 'выбор', 'займер', 'эпизод', 'client', 'мессенджер', 'credit', 'смотреть', 'официальный', 'ооо', 'личный', 'спорт', 'минут', 'качестве', 'текущие', 'магазин', 'отказа', 'embed', 'серия', 'app', 'ответы', 'наличными', 'микрозаймы', 'дней', 'магазине', 'рублей', 'фото', 'history', 'веб', 'payment', 'season', 'отзывы', 'россия', 'moneyman', 'фильм', 'банки', 'sezon', 'кабинет', 'регистрация', 'россии', 'видео', 'оформить', 'заявка', 'loan', 'срочно', 'займа', 'быстрые', 'цена', 'срочные', 'вход', 'story', 'заем', 'новых', 'история', 'video', 'хорошем', 'partner', 'cabinet', 'loans', 'сезон', 'турбозайм', 'step'}

In [42]:
def remove_words(set, cell):
    result = ''
    last = '...'
    for word in cell.split():
        if word in set and last!=word+' ':
            result += word + ' '
            last = word + ' '
    return result[:-1]

In [43]:
data['tokens3'] = data['tokens2']
data.tokens3.head(3)

0    форм мачеха работы пасынка горячую массаж маче...
1    platiza мобильные мобильные sergej code code c...
2    sims sims sims кредит языке разлива огромное о...
Name: tokens3, dtype: object

In [44]:
for i in range(len(data['tokens2'])):
    data['tokens3'][i] = remove_words(popular, data['tokens2'][i])
data.head(3)

/tmp/ipykernel_1200/4235025563.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tokens3'][i] = remove_words(popular, data['tokens2'][i])

,CLIENT_ID,RETRO_DT,tokens,urls_hashed,tokens2,tokens3
0,5909886,20200911,форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...,7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...,форм мачеха работы пасынка горячую массаж маче...,качестве видео история бесплатно смотреть vide...
1,1385448,20210519,platiza 1 мобильные 2 sergej 1 code 3 отказов ...,1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...,platiza мобильные мобильные sergej code code c...,деньги кабинет оформить credit history secure ...
2,1866195,20210913,sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...,6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...,sims sims sims кредит языке разлива огромное о...,кредит почта качестве игры бесплатно смотреть ...

In [ ]:
new_df = df['new_values'].str.split('\n',expand=True)

In [47]:
df_razbil = data['tokens3'].str.split(' ', expand=True)
df_razbil.head(3)

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
0,качестве,видео,история,бесплатно,смотреть,video,купить,магазине,хорошем,ответы,...,None,None,None,None,None,None,None,None,None,None
1,деньги,кабинет,оформить,credit,history,secure,новости,займов,купить,выбор,...,None,None,None,None,None,None,None,None,None,None
2,кредит,почта,качестве,игры,бесплатно,смотреть,фильмы,video,регистрация,новости,...,None,None,None,None,None,None,None,None,None,None

In [50]:
data_merged = pd.concat([data, df_razbil], axis=1)
data_merged.head(3)

,CLIENT_ID,RETRO_DT,tokens,urls_hashed,tokens2,tokens3,0,1,2,3,...,89,90,91,92,93,94,95,96,97,98
0,5909886,20200911,форм 1 мачеха 1 работы 1 пасынка 1 горячую 1 м...,7bbcc146c0ba4df814701ff7297b2205 1 ee0d49cbc99...,форм мачеха работы пасынка горячую массаж маче...,качестве видео история бесплатно смотреть vide...,качестве,видео,история,бесплатно,...,None,None,None,None,None,None,None,None,None,None
1,1385448,20210519,platiza 1 мобильные 2 sergej 1 code 3 отказов ...,1889e0cbd3e343e9521a07aa312257ac 2 8253d8d3a67...,platiza мобильные мобильные sergej code code c...,деньги кабинет оформить credit history secure ...,деньги,кабинет,оформить,credit,...,None,None,None,None,None,None,None,None,None,None
2,1866195,20210913,sims 3 кредит 1 языке 1 разлива 1 огромное 1 о...,6e617b4bfdbef85d8b09ec08ac72f0f2 1 94309f5f116...,sims sims sims кредит языке разлива огромное о...,кредит почта качестве игры бесплатно смотреть ...,кредит,почта,качестве,игры,...,None,None,None,None,None,None,None,None,None,None

In [64]:
data_merged.drop(['tokens', 'tokens2'], axis=1)
data_chist = data_merged[['CLIENT_ID', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,15,16,17,18,19,20 ]]
data_chist

,CLIENT_ID,0,1,2,3,4,5,6,7,8,...,11,12,13,14,15,16,17,18,19,20
0,5909886,качестве,видео,история,бесплатно,смотреть,video,купить,магазине,хорошем,...,None,None,None,None,None,None,None,None,None,None
1,1385448,деньги,кабинет,оформить,credit,history,secure,новости,займов,купить,...,video,личный,займы,society,заем,веб,наличными,заявка,всей,игры
2,1866195,кредит,почта,качестве,игры,бесплатно,смотреть,фильмы,video,регистрация,...,society,россия,цены,одноклассники,хорошем,ответы,None,None,None,None
3,1587081,деньги,кабинет,оформить,текущие,video,фильм,credit,войти,app,...,займов,купить,history,магазине,выбор,личный,займы,заем,наличными,заявка
4,1400908,деньги,минут,кабинет,текущие,credit,secure,сезон,личный,наличными,...,россии,цены,client,быстрые,москве,отзывы,календарь,цене,цена,contact
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302863,6220063,,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
302864,5543361,видео,игры,бесплатно,app,новости,отзывы,None,None,None,...,None,None,None,None,None,None,None,None,None,None
302865,224227891,деньги,кабинет,credit,secure,личный,наличными,цена,россия,цены,...,отзывы,цене,россии,client,компании,смотреть,бесплатно,вход,зарплаты,займа
302866,5909478,купить,video,магазине,society,story,всей,цены,payment,рублей,...,цене,цена,россии,amp,почта,история,бесплатно,магазин,фото,отзывы
302867,5536683,деньги,кабинет,сериал,video,фильм,amp,credit,новости,купить,...,сезон,оформить,дней,society,заем,наличными,заявка,story,спорт,sezon

In [88]:
pd.get_dummies(data_chist, columns=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [85]:
data_chist['val'] = data_chist['CLIENT_ID']

/tmp/ipykernel_1200/3800913803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_chist['val'] = data_chist['CLIENT_ID']

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
data_train, data_test, y_train, y_test = train_test_split(data, y, test_size=0.33, random_state=42)
# разбиение на тренировчоный и тестовый

In [ ]:
clf = tree.DecisionTreeClassifier(criterion='entropy')

In [ ]:
clf.fit(data_train, y_train)

In [ ]:
DecisionTreeClassifier(criterion='entropy')

In [ ]:
clf.score(data_test, y_test)

In [ ]:
from sklearn.model_selection import cross_val_score
scores_data = pd.DataFrame()
max_depth_value = range(1, 15)
for max_depth in max_depth_value:
    clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=max_depth)
    clf.fit(data_train, y_train)
    train_score = clf.score(data_train, y_train)
    test_score = clf.score(data_test, y_test)
    
    mean_cross_val = cross_val_score(clf, data_train, y_train, cv=2).mean()
    
    temp_scores_data = pd.DataFrame({'max_depth':[max_depth], 'train_score':[train_score],
                                     'test_scores':[test_score],
                                    'cross_val':[mean_cross_val]})

    
    scores_data = scores_data.append(temp_scores_data)

# зависимость скора на тренировочном, кросс-вал, тестовой выборке от глубины дерева

In [ ]:
scores_data_long = pd.melt(scores_data, id_vars=['max_depth'], value_vars=['train_score', 'test_scores', 'cross_val']
                           ,value_name='myVarname', var_name='Scores')
scores_data_long.head()

In [ ]:
sns.lineplot(data=scores_data_long, x="max_depth", y="myVarname", hue="Scores")
# графическая интерпритация полученных данных